"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const index_1 = require("../src/index");
const satoshi = new index_1.Wallet();
const bob = new index_1.Wallet();
const amount = 200;
const sender = satoshi.publicKey;
const receiver = bob.publicKey;
const transaction = new index_1.Transaction(amount, sender, receiver, Date.now());
console.log(`Amount Transacted: ${transaction.amount}`);
console.log(`From: ${sender}`);
console.log(`To: ${receiver}`);
console.log(`Transaction Hash: ${transaction.hash}`);
